emailapp/urls.py
from django.conf.urls import url
from . import views
from .views import Add_upload,composeview,Home,logout,Delete_mail
from django.conf import settings
urlpatterns = [
    url(r'person/$',views.persondetail),
    url(r'inbox/$',views.inbox),

    url(r'home/$',views.Home.as_view()),
    url(r'compose/$',composeview.as_view()),
    url(r'add/$',Add_upload.as_view()),
    url(r'delete/(?P<pk>[0-9]+)/$', Delete_mail.as_view()),
]

emailproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from emailapp.views import Main
from django.contrib.auth import views as auth_views
from emailapp import views as core_views
from emailapp.views import logout
from django.contrib.auth.views import logout
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^', include(router.urls)),
    url(r'^',include('emailapp.urls')),
    url(r'^login/$',auth_views.login,name='login'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^logout/$',logout, {'next_page':settings.LOGOUT_REDIRECT_URL},name='logout'),
    url(r'^$',Main.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

emailapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Person(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()

    def __str__(self):
        return str(self.email)

    def __unicode__(self):
        return unicode(self.email)


class Compose(models.Model):
    fromemail=models.EmailField()
    sendto=models.ForeignKey(Person)
    subject=models.CharField(max_length=100)
    content=models.TextField(max_length=500)

    def __str__(self):
        return str(self.sendto)

    def __unicode__(self):
        return unicode(self.sendto)

emailapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.


from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from emailapp.models import Person,Compose
from emailapp.serializers import PersonSerializer,ComposeSerializer
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic,View
from  django.shortcuts  import render_to_response
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect




@csrf_exempt
def persondetail(request):
    if request.method == 'GET':
        snippets = Person.objects.all()
        serializer = PersonSerializer(snippets, many=True)
        return render(request, "emailapp/person.html", {'serializer': serializer})

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = PersonSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/add')
    else:
        form = UserCreationForm()
    return render(request, 'emailapp/signup.html', {'form': form})


class Home(LoginRequiredMixin,View):
    def get(self, request):
        return render_to_response('emailapp/home.html')

class Main(View):
    def get(self, request):
        return render_to_response('emailapp/main.html')


from django.contrib.auth import logout

def logout_view(request):
    logout(request)

@csrf_exempt
def inbox(request):
    if request.method == 'GET':
        username = None
        if request.user.is_authenticated():
            username = request.user.username

        snippets = Compose.objects.filter(sendto__name=username)
        print (Compose.objects.filter(sendto__email="shankarswamy294@gmail.com"))
        serializer = ComposeSerializer(snippets, many=True)
        return render(request, "emailapp/inbox.html", {'serializer': serializer})

    if request.method == 'POST':
        return redirect('/inbox')

from django.views import View
from django.views.generic.edit import CreateView,DeleteView

class Add_upload(CreateView,View):
    model = Person
    context_object_name = "all_upload"
    fields = ["name","email"]
    success_url = "/home"


class composeview(CreateView,View):
    model = Compose
    context_object_name = "all_upload"
    fields = ["fromemail","sendto","subject","content"]
    success_url = "/home"

class Delete_mail(DeleteView):
    model = Compose
    context_object_name = "all_upload"
    template_name = "emailapp/mail_delete.html"
    success_url = '/inbox'

emailapp/templates/emailapp/compose_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        #home,#but1{
            margin:5px;
        }

        #id_sendto{
            border-radius:20px;
            padding:10px;
            border: 1px solid black;
            width:100%;
            margin:10px;
        }

        #id_fromemail,#id_subject{
        width:100%;
        border-radius:20px;
        height:1px;
        margin:10px;
        border:1px solid black;
        padding:18px;
    }
    textarea{
        width:100%;
        border-radius:20px;
        margin:10px;
        border:1px solid black;
        height:150px;
        padding:20px;
    }


    }
    #butt{
    width:10%;
    border-radius: 20px;
    }
    hr{
    border:2px solid black;
    }

         textarea:active,#id_sendto:active,#id_fromemail:active,#id_subject:active{
            outline: none;
        }
        textarea:focus,#id_sendto:focus,#id_fromemail:focus,#id_subject:focus{
            outline:none;
            }



    </style>

</head>
<body>
<div class="container">
     <div class="row" id="new_col">



                 <div class="col-md-12">
                    <form method="post" enctype="multipart/form-data">
                        <h1><strong>COMPOSE</strong></h1><hr/>
                        <div id="button1">
                        <input type="button" class="btn btn-success" onclick="location.href='/home';" id="home" value="Home"/>
                        <input type="button" class="btn btn-warning" onclick="location.href='/logout';" id="but1" value="Logout"/>
                        </div>
                        {% csrf_token %}
                            <table>
                                {{form.as_table}}
                            </table>
                            <div id="button"p>
                                <input id="demo_butt" class="btn btn-info" type ="button" onclick="check()" value="submit">
                                <input id="success_butt" class="btn btn-success" type ="submit" class="submit">
                        </div>
                        </form>

    </div>
</div>
    </div>


<script>
    function check(){
        var check_string=["bomb","exploid","rdx","RDX","war"];
        content=document.getElementById('id_content').value;
        content=content.split(" ");
        var c=0;
        for(i in check_string){
            for(j in content){
                if(check_string[i] === content[j]){
                    c+=1;
                }
            }
        }

        if(c==0){
            x=document.getElementById('success_butt');
            x.click();
        }else{
            alert("your mail consists of offensive words");
        }
    }
</script>
</body>
</html>

emailapp/templates/emailapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        #butt{
            margin-top:20%;
            text-align: center;
        }
        #but1,#but2,#but3{
        margin:20px;
        }


        #compose,#logout,#inbox{
            height:100px;
            margin-left:130px;
        }
        #welcome{
        margin-top:140px;
        margin-bottom:40px;
        }

        @media (max-width:600px){
                    #compose,#logout,#inbox{
            height:100px;
            margin-left:130px;
        }
        #welcome{
        margin-top:0px;
        margin-bottom:0px;
        }
        }
    </style>
</head>
<body>
<div class="container text-center" id="welcome">
        <div class="row">
            <div class="col-md-12">

                <h1>Welcome back....!!</h1>
            </div>
            </div>
    </div>

<div class="container text-center">
        <div class="row">
            <div class="col-md-4">
                <img id="inbox" src="{% static 'emailapp/inbox_icon.png' %}" class="img-responsive">
                <input type="button" class="btn btn-success" onclick="location.href='/inbox';" id="but1" value="Inbox"/>
            </div>

            <div class="col-md-4">
                <img id="compose" src="{% static 'emailapp/compose_icon.png' %}" class="img-responsive">
                <input type="button" class="btn btn-info" onclick="location.href='/compose';" id="but2" value="Compose"/>
            </div>

            <div class="col-md-4">
                <img id="logout" src="{% static 'emailapp/logout_icon.png' %}" class="img-responsive">
                <input type="button"  class="btn btn-warning" onclick="location.href='/logout';" id="but3" value="Logout"/>
            </div>

        </div>
    </div>


</body>
</html>

emailapp/templates/emailapp/inbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>inbox</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        #button{
            margin-left:80%;
        }
        #home,#but1{
            margin:10px;
        }
        #email_element{
        margin-bottom:10px;
        border-radius:20px;
        }
    </style>
</head>
<body>

<div class="container">
<h1>INBOX</h1>
<hr/>
    <div id="button">
<input type="button" class="btn btn-success" onclick="location.href='/home';" id="home" value="Home"/>
<input type="button" class="btn btn-warning" onclick="location.href='/logout';" id="but1" value="Logout"/>
    </div>
<ul style="list-style-type: none;">
    <li>

        {% csrf_token %}
    {% for i in serializer.data reversed %}
        <div id="email_element" class="panel-body bg-info">
        From email: {{ i.fromemail }}<br><br>
        Subject: {{ i.subject }}<br><br>
        Content :  {{ i.content }} <br><br>
        <div id="x{{ i.id }}"></div>
       <!-- <input type="button" class="btn btn-info" id="delete{{ i.id }}" onclick="location.href='/delete/{{ i.id }}';" value="Delete">
        -->
        <input type="button" class="btn btn-info" id="delete{{ i.id }}" onclick="dodelete({{ i.id }})" value="Delete">

        </div>
    {% endfor %}
    </li>
</ul>
</div>


<script>
    var flag=0;
    function dodelete(x){

        console.log("--->",x)
        var xhttp=new XMLHttpRequest();
        xhttp.onreadystatechange = function(){
        if(this.readyState == 4 && this.status == 200){
            document.getElementById("delete"+x).style.display = 'none';
            document.getElementById("x"+x).innerHTML = this.responseText;
        }
        };
        xhttp.open("GET","/delete/"+x,true);
        xhttp.send();
        flag = 1;

        console.log("comes here");
        document.getElementById("do_this").onClick
        var xhttp=new XMLHttpRequest();
        xhttp.onreadystatechange = function(){
        if(this.readyState == 4 && this.status == 200){
            document.getElementById("delete"+x).style.display = 'none';
            document.getElementById("x"+x).innerHTML = this.responseText;
        }
        };
        xhttp.send("DELETE","/delete/"+x,true);
        //xhttp.send();
        }


</script>


</body>
</html>

emailapp/templates/emailapp/mail_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div id="del" class="container text-danger" >
<form method="post">
        {% csrf_token %}
        <table>
            <p>Do you want to delete this mail</p>
        </table>
        <input class="btn btn-success" type ="submit" value="Yes" placeholder=" confirm delete">
        <input class="btn btn-danger" type ="button" value="No" onclick="location.href='/inbox';">
    </form>
</div>


</body>
</html>

emailapp/templates/emailapp/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FRENDZOO</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
     .carousel-caption{
  			top: 50%;
  			transform: translateY(-50%);
  			text-transform: uppercase;
  		}

        #icon{
  			max-width: 200px;
  			margin 1% auto;
  		}
  		.btn{ma
  			font-size: 18px;
  			color: #FFF;
  			padding: 12px 22px;
  			background-color: #5E4485;
  			border: 2px solid #FFF;
  		}

  		@media (max-width: 600px){
  			.carousel-caption{
  				margin-bottom:-170px;
  			}
  			.btn{
  			font-size: 12px;
  			color: #FFF;
  			padding: 12px 22px;
  			background-color: #5E4485;
  			border: 2px solid #FFF;
  		}
  			#icon{
  				max-width: 150px;
  			}
  		}
  		#about_img,#shankar{
  		    border-radius: 10%;
  		}

  		#resume{
  		    border-radius:30%;
  		}
  		.about_head{
  		    font-size:bold;
  		    margin-top:70px;
  		    margin-bottom:50px;
  		}
  		.about_tech,#about_para{
  		    font-size:20px;
  		    padding:30px;
  		}
  		ul{
  		list-style:none;
  		}
  		li{
  		font-size:bold;
  		}

        #icon{
  			max-width: 200px;
  			margin 1% auto;
  		}
  		footer{
  			width:100%;
  			background-color: #5E4485;
  			padding: 3%;
  			color: #FFF;
  		}

  		.fa{
  			padding: 25px;
  			font-size: 50px;
  			color: #FFF;
  		}

  		.fa:hover{
  			color: #D5D5D5;
  			text-decoration: none;
  		}
  		#shankar,#resume{
  		    height:200px;
  		    margin-left:60px;
  		}
    </style>
</head>
<body>
<!--<div class="container" id="cont">
--<h1>FRANZOO MAIL</h1>
<input class="btn btn-success" type="button"  onclick="location.href='/login';" id="but1" value="Login"/>
<input class="btn btn-warning" type="button"  onclick="location.href='/signup';" id="but2" value="Signup"/>
</div>-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" ></li>
        <li data-target="#myCarousel" data-slide-to="2" ></li>
    </ol>

    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'emailapp/bg1.jpg' %}">
            <div class="carousel-caption">
                <h1>FRANZOO MAIL</h1>
                    <input class="btn btn-success" type="button"  onclick="location.href='/login';" id="but1" value="Login"/>
                    <input class="btn btn-warning" type="button"  onclick="location.href='/signup';" id="but2" value="Signup"/>
            </div>
        </div>

        <div class="item">
            <img src="{% static 'emailapp/snow.png' %}">
            <div class="carousel-caption">
                <h1>FRANZOO MAIL</h1>
                    <input class="btn btn-success" type="button"  onclick="location.href='/login';" id="but1" value="Login"/>
                    <input class="btn btn-warning" type="button"  onclick="location.href='/signup';" id="but2" value="Signup"/>
            </div>
        </div>

                <div class="item">
            <img src="{% static 'emailapp/red.png' %}">
            <div class="carousel-caption">
                <h1>FRANZOO MAIL</h1>
                    <input class="btn btn-success" type="button"  onclick="location.href='/login';" id="but1" value="Login"/>
                    <input class="btn btn-warning" type="button"  onclick="location.href='/signup';" id="but2" value="Signup"/>
            </div>
        </div>

        </div>

<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	<span class="sr-only">Previous</span>
	</a>


	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
	<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	<span class="sr-only">Next</span>
	</a>
</div>

<!--
<div class="container text-center">
    <div class="row">
        <h1 class="about_head">ABOUT PROJECT</h1>
        <div class="col-md-8" id="about_para">
            <p>FRANDZOO Mail is a web application in which user can send and receive mails from other user. Frandzoo mail runs a script which discards offensive mail being sent by the user.</p>
        </div>
        <div class="col-md-4">
           <img id="about_img" src="{% static 'emailapp/about.png' %}" class="img-responsive">
        </div>
    </div>
</div>

    <div class="container text-center">
        <div class="row">
            <h1 class="about_head">PORTFOLIO</h1>
            <div class="col-md-4">
                <img id="shankar" src="{% static 'emailapp/shankar.png' %}" class="img-responsive">
                <h4>Shankar Swamy</h4>
            </div>
            <div class="col-md-4">

                <div class="about_tech">
                <ul>
                    <h3>TECHNICAL SKILLS</h3>
                    <li >C, Python, Django</li>
                    <li >Nodejs, Javascript, Jquery</li>
                    <li >Html, Css</li>
                </ul>
                    </div>
            </div>
            <div class="col-md-4">
                <a download="resume.docx" href="{% static 'emailapp/resume.docx' %}">
                    <img id="resume" src="{% static 'emailapp/resume.png' %}" class="img-responsive">
                </a>
                <h4>Resume</h4>
            </div>
        </div>
    </div>


    <footer class="container-fluid text-center">
	    <div class="row">
			<h3>Connect</h3>
			<a href="https://www.facebook.com/shankar.swamy.9" class="fa fa-facebook"></a>
			<a href="https://twitter.com/shankarswamy294" class="fa fa-twitter"></a>
			<a href="https://www.linkedin.com/in/shankar-swamy-424323b9" class="fa fa-linkedin"></a>
			<a href="https://www.instagram.com/shankar_swamy" class="fa fa-instagram"></a>
			<a href="https://github.com/shankarswamy294" class="fa fa-github"></a>
		</div>

</footer>
-->
</body>
</html>

emailapp/templates/emailapp/person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<h1><b>HII GUYS...!!!</b></h1>
<input type="button"  onclick="location.href='/logout';" id="but1" value="Logout"/>
    {% for i in serializer.data %}
       name :  {{ i.name }} <br><br>
       email : {{ i.email }} <br><br>
    {% endfor %}
</body>
</html>

emailapp/templates/emailapp/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>



        #home{
                margin-top:50px;
                margin-left:40px;

            }

            .button{
                text-align:center;
                margin-left:20px;
                margin-bottom:20px;
            }

            #id_email,#id_name{
             background-color:transparent;
             border:2px solid white;
             border-radius:20px;
             height:35px;
             padding-left:20px;
             margin-left:10px;
             margin-top:20px;
            }

            #but{
            margin:5px;
            }


        #id_email:focus,#id_name:focus{
            outline: none;
        }

        #id_email:active,#id_name:active{
            outline: none;
        }


         #start{
            padding:20px;
            border: 0px solid white;
            border-radius:20px;
            margin-top:150px;
            -webkit-box-shadow: 1px 0px 26px 0px rgba(247,239,247,1);
            -moz-box-shadow: 1px 0px 26px 0px rgba(247,239,247,1);
            box-shadow: 1px 0px 26px 0px rgba(247,239,247,1);
         }

         body{
         color:white;
         background:url({% static 'emailapp/pdetails.jpg' %}) no-repeat;
         width:100%;
         height:100vh   ;
         }


    </style>

</head>
<body>
<!--
<div class="container">
    <div class="row" id="new_col">
                 <div class="col-md-4">
                 </div>


        <div class="col-md-4" id="about_para">

            <form method="post" enctype="multipart/form-data">
                <h1>Personal Details</h1>
                    {% csrf_token %}
                    <table>
                        {{form.as_table}}
                    </table>
                    <div id="button">
                        <input class="btn btn-success" type ="submit" id="but" class="submit">
                    </div>
            </form>

        </div>

        <div class="col-md-4">
                 </div>
    </div>
    -->


<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
        <div class="col-md-4 col-sm-4 col-xs-4 text-center">

            <form method="post">
                <div id="start">
                <h1>Personal Details</h1>
                    {% csrf_token %}
                    <table>
                        {{form.as_table}}
                    </table>
                    <div id="button">
                        <input class="btn btn-success" type ="submit" id="but" class="submit">
                    </div>
                </div>
            </form>

        </div>
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
    </div>
</div>

</body>
</html>

emailapp/templates/emailapp/post_confirm_delete.html
<form action="" method="post">{% csrf_token %}
   <p>Are you sure you want to delete "{{ object }}"?</p>
   <input type="submit" value="Confirm" />
</form>

emailapp/templates/emailapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
 #home{
        margin-top:50px;
        margin-left:40px;

    }

    .button{
        text-align:center;
        margin-left:20px;
        margin-bottom:20px;
    }

    #id_password1,#id_password2,#id_username{
     background-color:transparent;
     border:2px solid white;
     border-radius:20px;
     height:35px;
     padding-left:20px;
     margin-left:10px;
     margin-top:20px;
    }

    #newbut,#newbut1{
    margin:5px;
    }

    #id_password:active,#id_username:active{
            outline: none;
        }
        #id_password:focus,#id_username:focus{
            outline:none;
            }
   ul{
   list-decoration:none;
   }
 #start{
     padding-top:20px;
     padding-bottom:20px;
    padding-left:20px;
    border: 0px solid white;
    border-radius:20px;
    margin-top:50px;
    -webkit-box-shadow: 1px 0px 26px 0px rgba(247,239,247,1);
    -moz-box-shadow: 1px 0px 26px 0px rgba(247,239,247,1);
    box-shadow: 1px 0px 26px 0px rgba(247,239,247,1);
 }

 body{
 color:white;
 background:url({% static 'emailapp/signup1.jpg' %}) no-repeat;
 width:100%;
 height:100vh   ;
 }

    </style>
</head>
<body>
<!--
    <div class="container">
  <h2><strong>Sign up</strong></h2><hr>
    <input type="button" class="btn btn-responsive btn-warning" onclick="location.href='/logout';" id="but1" value="back"/>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button id="button" class="btn btn-responsive btn-info" type="submit">Sign up</button>
  </form>
  -->


<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-4">
            <input type="button" class="btn btn-success" onclick="location.href='/';" id="home" value="Home"/>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
        <div class="col-md-4 col-sm-4 col-xs-4"></div>
    </div>
</div>

<div class="container-fluid ">
    <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-2"></div>
        <div class="col-md-8 col-sm-8 col-xs-8">

            <form method="post">
                <div id="start">
                <h1>SignUp</h1>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button id="button" class="btn btn-responsive btn-info" type="submit">Sign up</button>
                </div>

            </form>

        </div>
        <div class="col-md-2 col-sm-2 col-xs-2"></div>
    </div>
</div>
  </div>
</body>
</html>